### PR TITLE
feat: use faster isal when available

### PR DESCRIPTION
**Pull request by bdraco**
isal recommended for speed by pycompression authors https://github.com/pycompression/python-zlib-ng/pull/24#issuecomment-1871816603

Tested on x86_64, macos arm64, and aarch64

### CODE REVIEW

**Comment by rhpvorderman** [comment]
As a general comment: isa-l compresses to much lower compression levels by default. In case that is undesirable, it is better to use zlib-ng.

On the other hand, if deflate compression is bottlenecking, shaving another 20% of the filesize is not really worth the delay in latency sensitive situations. The difference in speed between zlib-ng level 2 and isa-l level 2 will be much less than the difference between isa-l level 2 (default) and zlib-ng level 6 (default).

zlib-ng level 1 is much bigger than either zlib level 1 or isa-l level 1, at least on genomic data. So I don't recommend using that.

**Comment by bdraco** [comment]
Seems to be a better trade off with using isal. It's faster and we get better compression for the websocket use case

**Comment by rhpvorderman** [comment]
Then they are probably already using level 1. Then ISA-L is so much better. The compression speed is incredible, almost as fast as the decompression speed, 5 times faster than zlib. It really is an incredible library. I prefer using ISA-L where I can, and I maintain python-zlib-ng only because python-isal cannot cover all use cases. So all the cool innovations happen in python-isal first and are then ported over later when they proved stable.

**Comment by rhpvorderman** [comment]
I wonder, have you considered porting this work over to aiohttp directly? In that way everyone will benefit from your work.

**Comment by bdraco** [comment]
That's the eventual plan.

Usually I try out changes in libraries for a few months before upstreaming them into aiohttp.

**Pull request merged**
